//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tibialyzer.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AboutTab {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutTab() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tibialyzer.Translation.AboutTab", typeof(AboutTab).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Resources.
        /// </summary>
        internal static string additionalResourcesHeader {
            get {
                return ResourceManager.GetString("additionalResourcesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoHotkey Guide.
        /// </summary>
        internal static string autoHotkeyGuideButton {
            get {
                return ResourceManager.GetString("autoHotkeyGuideButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Commands.
        /// </summary>
        internal static string customCommandsGuideButton {
            get {
                return ResourceManager.GetString("customCommandsGuideButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Meter Guide.
        /// </summary>
        internal static string damageMeterGuideButton {
            get {
                return ResourceManager.GetString("damageMeterGuideButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Guide.
        /// </summary>
        internal static string informationGuideButton {
            get {
                return ResourceManager.GetString("informationGuideButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Start Guide.
        /// </summary>
        internal static string quickStartGuideButton {
            get {
                return ResourceManager.GetString("quickStartGuideButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot Guide.
        /// </summary>
        internal static string screenshotGuideButton {
            get {
                return ResourceManager.GetString("screenshotGuideButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Guide.
        /// </summary>
        internal static string settingsGuideButton {
            get {
                return ResourceManager.GetString("settingsGuideButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tibialyzer is a tool designed to assist you in playing Tibia. It is a completely free and open source product.
        ///
        ///- If you paid any money for Tibialyzer, you got scammed and should request a refund.
        ///- If you downloaded Tibialyzer from anywhere but the official Github repository, your copy of Tibialyzer might not be safe. Only download Tibialyzer from the official Github repository..
        /// </summary>
        internal static string tibialyzerAboutText {
            get {
                return ResourceManager.GetString("tibialyzerAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tibialyzer 1.4.0.
        /// </summary>
        internal static string tibialyzerVersionHeader {
            get {
                return ResourceManager.GetString("tibialyzerVersionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tibia Updated, What Now?.
        /// </summary>
        internal static string tibiaUpdatedWhatNowButton {
            get {
                return ResourceManager.GetString("tibiaUpdatedWhatNowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Tibialyzer.
        /// </summary>
        internal static string updatingTibialyzerButton {
            get {
                return ResourceManager.GetString("updatingTibialyzerButton", resourceCulture);
            }
        }
    }
}
