//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tibialyzer.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdvancedTab {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdvancedTab() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tibialyzer.Translation.AdvancedTab", typeof(AdvancedTab).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string applyConvertRatioButton {
            get {
                return ResourceManager.GetString("applyConvertRatioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string applyDiscardRatioButton {
            get {
                return ResourceManager.GetString("applyDiscardRatioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string applySQLQueryButton {
            get {
                return ResourceManager.GetString("applySQLQueryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string applyValueConvertButton {
            get {
                return ResourceManager.GetString("applyValueConvertButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string applyValueDiscardButton {
            get {
                return ResourceManager.GetString("applyValueDiscardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold/Cap Convert Ratio.
        /// </summary>
        internal static string customConvertRatioHeader {
            get {
                return ResourceManager.GetString("customConvertRatioHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold/Cap Discard Ratio.
        /// </summary>
        internal static string customDiscardRatioHeader {
            get {
                return ResourceManager.GetString("customDiscardRatioHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Properties.
        /// </summary>
        internal static string itemPropertiesHeader {
            get {
                return ResourceManager.GetString("itemPropertiesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Query.
        /// </summary>
        internal static string sqlQueryHeader {
            get {
                return ResourceManager.GetString("sqlQueryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Convert Ratio.
        /// </summary>
        internal static string valueConvertRatioHeader {
            get {
                return ResourceManager.GetString("valueConvertRatioHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Discard Ratio.
        /// </summary>
        internal static string valueDiscardRatioHeader {
            get {
                return ResourceManager.GetString("valueDiscardRatioHeader", resourceCulture);
            }
        }
    }
}
