//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tibialyzer.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AutoHotkeyTab {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AutoHotkeyTab() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tibialyzer.Translation.AutoHotkeyTab", typeof(AutoHotkeyTab).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor.
        /// </summary>
        internal static string anchorHeader {
            get {
                return ResourceManager.GetString("anchorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string autoHotkeyDownloadHeader {
            get {
                return ResourceManager.GetString("autoHotkeyDownloadHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string autoHotkeyOptionsHeader {
            get {
                return ResourceManager.GetString("autoHotkeyOptionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoHotkey Script.
        /// </summary>
        internal static string autoHotkeyScriptHeader {
            get {
                return ResourceManager.GetString("autoHotkeyScriptHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Suspended Window.
        /// </summary>
        internal static string closeSuspendedWindowButton {
            get {
                return ResourceManager.GetString("closeSuspendedWindowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download AutoHotkey.
        /// </summary>
        internal static string downloadAutoHotkeyButton {
            get {
                return ResourceManager.GetString("downloadAutoHotkeyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download AutoHotkey to the temporary directory and launches an installer. Complete the installer to install AutoHotkey..
        /// </summary>
        internal static string downloadAutoHotkeyButtonTooltip {
            get {
                return ResourceManager.GetString("downloadAutoHotkeyButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Script On Exit.
        /// </summary>
        internal static string exitScriptOnExitCheckbox {
            get {
                return ResourceManager.GetString("exitScriptOnExitCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position (Offset).
        /// </summary>
        internal static string positionOffsetHeader {
            get {
                return ResourceManager.GetString("positionOffsetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown AutoHotkey.
        /// </summary>
        internal static string shutdownAutoHotkeyButton {
            get {
                return ResourceManager.GetString("shutdownAutoHotkeyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re(start) AutoHotkey.
        /// </summary>
        internal static string startAutoHotkeyButton {
            get {
                return ResourceManager.GetString("startAutoHotkeyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string startAutoHotkeyHeader {
            get {
                return ResourceManager.GetString("startAutoHotkeyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Script On StartUp.
        /// </summary>
        internal static string startScriptOnStartupBox {
            get {
                return ResourceManager.GetString("startScriptOnStartupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Left.
        /// </summary>
        internal static string suspendedAnchorDropDownList_0 {
            get {
                return ResourceManager.GetString("suspendedAnchorDropDownList_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Right.
        /// </summary>
        internal static string suspendedAnchorDropDownList_1 {
            get {
                return ResourceManager.GetString("suspendedAnchorDropDownList_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Left.
        /// </summary>
        internal static string suspendedAnchorDropDownList_2 {
            get {
                return ResourceManager.GetString("suspendedAnchorDropDownList_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Right.
        /// </summary>
        internal static string suspendedAnchorDropDownList_3 {
            get {
                return ResourceManager.GetString("suspendedAnchorDropDownList_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The screen anchor to which the offsets should be applied..
        /// </summary>
        internal static string suspendedAnchorDropDownListTooltip {
            get {
                return ResourceManager.GetString("suspendedAnchorDropDownListTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Suspended Window.
        /// </summary>
        internal static string suspendedTestButton {
            get {
                return ResourceManager.GetString("suspendedTestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing.
        /// </summary>
        internal static string testingHeader {
            get {
                return ResourceManager.GetString("testingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Offset.
        /// </summary>
        internal static string xOffsetLabel {
            get {
                return ResourceManager.GetString("xOffsetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Offset.
        /// </summary>
        internal static string yOffsetLabel {
            get {
                return ResourceManager.GetString("yOffsetLabel", resourceCulture);
            }
        }
    }
}
