//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tibialyzer.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BrowseTab {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BrowseTab() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tibialyzer.Translation.BrowseTab", typeof(BrowseTab).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creatures.
        /// </summary>
        internal static string browseTypeDropDownList_0 {
            get {
                return ResourceManager.GetString("browseTypeDropDownList_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string browseTypeDropDownList_1 {
            get {
                return ResourceManager.GetString("browseTypeDropDownList_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPCs.
        /// </summary>
        internal static string browseTypeDropDownList_2 {
            get {
                return ResourceManager.GetString("browseTypeDropDownList_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunting Places.
        /// </summary>
        internal static string browseTypeDropDownList_3 {
            get {
                return ResourceManager.GetString("browseTypeDropDownList_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quests.
        /// </summary>
        internal static string browseTypeDropDownList_4 {
            get {
                return ResourceManager.GetString("browseTypeDropDownList_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mounts.
        /// </summary>
        internal static string browseTypeDropDownList_5 {
            get {
                return ResourceManager.GetString("browseTypeDropDownList_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outfits.
        /// </summary>
        internal static string browseTypeDropDownList_6 {
            get {
                return ResourceManager.GetString("browseTypeDropDownList_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Database.
        /// </summary>
        internal static string searchDatabaseHeader {
            get {
                return ResourceManager.GetString("searchDatabaseHeader", resourceCulture);
            }
        }
    }
}
