//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tibialyzer.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DatabaseTab {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DatabaseTab() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tibialyzer.Translation.DatabaseTab", typeof(DatabaseTab).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Presets.
        /// </summary>
        internal static string conversionPresetsHeader {
            get {
                return ResourceManager.GetString("conversionPresetsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Item Conversion.
        /// </summary>
        internal static string databaseItemsHeader {
            get {
                return ResourceManager.GetString("databaseItemsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Settings.
        /// </summary>
        internal static string defaultSettingsButton {
            get {
                return ResourceManager.GetString("defaultSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mage (Creature Products).
        /// </summary>
        internal static string mageCreatureProductsButton {
            get {
                return ResourceManager.GetString("mageCreatureProductsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mage (No Creature Products).
        /// </summary>
        internal static string mageNoCreatureProductsButton {
            get {
                return ResourceManager.GetString("mageNoCreatureProductsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Gold Coins.
        /// </summary>
        internal static string noGoldCoinButton {
            get {
                return ResourceManager.GetString("noGoldCoinButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuables Only (&gt;1000G).
        /// </summary>
        internal static string valuablesOnly1KButton {
            get {
                return ResourceManager.GetString("valuablesOnly1KButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuables Only (&gt;5000G).
        /// </summary>
        internal static string valuablesOnly5KButton {
            get {
                return ResourceManager.GetString("valuablesOnly5KButton", resourceCulture);
            }
        }
    }
}
