//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tibialyzer.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HUDTab {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HUDTab() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tibialyzer.Translation.HUDTab", typeof(HUDTab).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Options.
        /// </summary>
        internal static string advancedOptionsButton {
            get {
                return ResourceManager.GetString("advancedOptionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always Show HUD.
        /// </summary>
        internal static string alwaysShowHUDCheckbox {
            get {
                return ResourceManager.GetString("alwaysShowHUDCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Left.
        /// </summary>
        internal static string anchorDropDownList_0 {
            get {
                return ResourceManager.GetString("anchorDropDownList_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Right.
        /// </summary>
        internal static string anchorDropDownList_1 {
            get {
                return ResourceManager.GetString("anchorDropDownList_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Left.
        /// </summary>
        internal static string anchorDropDownList_2 {
            get {
                return ResourceManager.GetString("anchorDropDownList_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Right.
        /// </summary>
        internal static string anchorDropDownList_3 {
            get {
                return ResourceManager.GetString("anchorDropDownList_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string anchorDropDownList_4 {
            get {
                return ResourceManager.GetString("anchorDropDownList_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor.
        /// </summary>
        internal static string anchorHeader {
            get {
                return ResourceManager.GetString("anchorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All HUDs.
        /// </summary>
        internal static string closeAllHudsButton {
            get {
                return ResourceManager.GetString("closeAllHudsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close HUD.
        /// </summary>
        internal static string closeHudButton {
            get {
                return ResourceManager.GetString("closeHudButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display HUD Text.
        /// </summary>
        internal static string displayHUDTextCheckbox {
            get {
                return ResourceManager.GetString("displayHUDTextCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Options.
        /// </summary>
        internal static string displayOptionsHeader {
            get {
                return ResourceManager.GetString("displayOptionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        internal static string fontSizeHeader {
            get {
                return ResourceManager.GetString("fontSizeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string heightLabel {
            get {
                return ResourceManager.GetString("heightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUD Type List.
        /// </summary>
        internal static string hudTypeListHeader {
            get {
                return ResourceManager.GetString("hudTypeListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        internal static string opacityLabel {
            get {
                return ResourceManager.GetString("opacityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position (Offset).
        /// </summary>
        internal static string positionOffsetHeader {
            get {
                return ResourceManager.GetString("positionOffsetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show HUD.
        /// </summary>
        internal static string showHudButton {
            get {
                return ResourceManager.GetString("showHudButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show HUD on Startup.
        /// </summary>
        internal static string showHudOnStartupCheckbox {
            get {
                return ResourceManager.GetString("showHudOnStartupCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string sizeHeader {
            get {
                return ResourceManager.GetString("sizeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string sizeLabel {
            get {
                return ResourceManager.GetString("sizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup.
        /// </summary>
        internal static string startupHeader {
            get {
                return ResourceManager.GetString("startupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string widthLabel {
            get {
                return ResourceManager.GetString("widthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Offset.
        /// </summary>
        internal static string xOffsetLabel {
            get {
                return ResourceManager.GetString("xOffsetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Offset.
        /// </summary>
        internal static string yOffsetLabel {
            get {
                return ResourceManager.GetString("yOffsetLabel", resourceCulture);
            }
        }
    }
}
