//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tibialyzer.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainTab {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainTab() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tibialyzer.Translation.MainTab", typeof(MainTab).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically Detect Character.
        /// </summary>
        internal static string automaticallyDetectCharacterCheckbox {
            get {
                return ResourceManager.GetString("automaticallyDetectCharacterCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically Download Addresses.
        /// </summary>
        internal static string automaticallyDownloadAddressesCheckbox {
            get {
                return ResourceManager.GetString("automaticallyDownloadAddressesCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically download memory addresses whenever Tibialyzer starts up..
        /// </summary>
        internal static string automaticallyDownloadAddressesCheckboxTooltip {
            get {
                return ResourceManager.GetString("automaticallyDownloadAddressesCheckboxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Names.
        /// </summary>
        internal static string characterNamesHeader {
            get {
                return ResourceManager.GetString("characterNamesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrome.
        /// </summary>
        internal static string chromeFlashClientButton {
            get {
                return ResourceManager.GetString("chromeFlashClientButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        internal static string classicClientButton {
            get {
                return ResourceManager.GetString("classicClientButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Issues.
        /// </summary>
        internal static string commonIssuesButton {
            get {
                return ResourceManager.GetString("commonIssuesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download New Addresses.
        /// </summary>
        internal static string downloadNewAddressesButton {
            get {
                return ResourceManager.GetString("downloadNewAddressesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads new memory addresses from the Tibialyzer GitHub page. Use this after an update when Tibialyzer breaks (note that it only works after I have updated the addresses there)..
        /// </summary>
        internal static string downloadNewAddressesButtonTooltip {
            get {
                return ResourceManager.GetString("downloadNewAddressesButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Command.
        /// </summary>
        internal static string executeCommandButton {
            get {
                return ResourceManager.GetString("executeCommandButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute a Tibialyzer command directly..
        /// </summary>
        internal static string executeCommandButtonTooltip {
            get {
                return ResourceManager.GetString("executeCommandButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Tibialyzer Command.
        /// </summary>
        internal static string executeTibialyzerCommandHeader {
            get {
                return ResourceManager.GetString("executeTibialyzerCommandHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firefox.
        /// </summary>
        internal static string firefoxFlashClientButton {
            get {
                return ResourceManager.GetString("firefoxFlashClientButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Partial Addresses.
        /// </summary>
        internal static string generatePartialAddressesButton {
            get {
                return ResourceManager.GetString("generatePartialAddressesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads a subset of the memory addresses from another GitHub page. This guy usually updates addresses faster than me, but he doesn&apos;t have all the addresses Tibialyzer requires. You can try using this if I haven&apos;t updated the addresses yet..
        /// </summary>
        internal static string generatePartialAddressesButtonTooltip {
            get {
                return ResourceManager.GetString("generatePartialAddressesButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started Guide.
        /// </summary>
        internal static string gettingStartedGuideButton {
            get {
                return ResourceManager.GetString("gettingStartedGuideButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started Video.
        /// </summary>
        internal static string gettingStartedVideoButton {
            get {
                return ResourceManager.GetString("gettingStartedVideoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string languageDropDownList_0 {
            get {
                return ResourceManager.GetString("languageDropDownList_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nederlands.
        /// </summary>
        internal static string languageDropDownList_1 {
            get {
                return ResourceManager.GetString("languageDropDownList_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polskie.
        /// </summary>
        internal static string languageDropDownList_2 {
            get {
                return ResourceManager.GetString("languageDropDownList_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português.
        /// </summary>
        internal static string languageDropDownList_3 {
            get {
                return ResourceManager.GetString("languageDropDownList_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the language Tibialyzer is displayed in. A language change requires a restart..
        /// </summary>
        internal static string languageDropDownListTooltip {
            get {
                return ResourceManager.GetString("languageDropDownListTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string languageSelectionHeader {
            get {
                return ResourceManager.GetString("languageSelectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string otherFlashClientButton {
            get {
                return ResourceManager.GetString("otherFlashClientButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        internal static string resourcesHeader {
            get {
                return ResourceManager.GetString("resourcesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tibia 11.
        /// </summary>
        internal static string tibia11ClientButton {
            get {
                return ResourceManager.GetString("tibia11ClientButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tibia Client Selection.
        /// </summary>
        internal static string tibiaClientSelectionHeader {
            get {
                return ResourceManager.GetString("tibiaClientSelectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Database.
        /// </summary>
        internal static string updateDatabaseButton {
            get {
                return ResourceManager.GetString("updateDatabaseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads an updated copy of the database from the GitHub page. Use this if the database has been updated with new creatures/items from e.g. a new update or new information on tibia.wikia. Requires a restart of Tibialyzer..
        /// </summary>
        internal static string updateDatabaseButtonTooltip {
            get {
                return ResourceManager.GetString("updateDatabaseButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Memory Addresses.
        /// </summary>
        internal static string updateMemoryAddressesHeader {
            get {
                return ResourceManager.GetString("updateMemoryAddressesHeader", resourceCulture);
            }
        }
    }
}
