//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tibialyzer.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NotificationsTab {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationsTab() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tibialyzer.Translation.NotificationsTab", typeof(NotificationsTab).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor.
        /// </summary>
        internal static string anchorHeader {
            get {
                return ResourceManager.GetString("anchorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply These Settings To All.
        /// </summary>
        internal static string applyTheseSettingsToAllButton {
            get {
                return ResourceManager.GetString("applyTheseSettingsToAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply the settings of this notification type to all notifications..
        /// </summary>
        internal static string applyTheseSettingsToAllButtonTooltip {
            get {
                return ResourceManager.GetString("applyTheseSettingsToAllButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Display.
        /// </summary>
        internal static string clearDisplayButton {
            get {
                return ResourceManager.GetString("clearDisplayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group 1.
        /// </summary>
        internal static string displayGroupDropDownList_0 {
            get {
                return ResourceManager.GetString("displayGroupDropDownList_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group 2.
        /// </summary>
        internal static string displayGroupDropDownList_1 {
            get {
                return ResourceManager.GetString("displayGroupDropDownList_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group 3.
        /// </summary>
        internal static string displayGroupDropDownList_2 {
            get {
                return ResourceManager.GetString("displayGroupDropDownList_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group 4.
        /// </summary>
        internal static string displayGroupDropDownList_3 {
            get {
                return ResourceManager.GetString("displayGroupDropDownList_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group 5.
        /// </summary>
        internal static string displayGroupDropDownList_4 {
            get {
                return ResourceManager.GetString("displayGroupDropDownList_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group 6.
        /// </summary>
        internal static string displayGroupDropDownList_5 {
            get {
                return ResourceManager.GetString("displayGroupDropDownList_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group 7.
        /// </summary>
        internal static string displayGroupDropDownList_6 {
            get {
                return ResourceManager.GetString("displayGroupDropDownList_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group 8.
        /// </summary>
        internal static string displayGroupDropDownList_7 {
            get {
                return ResourceManager.GetString("displayGroupDropDownList_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group 9.
        /// </summary>
        internal static string displayGroupDropDownList_8 {
            get {
                return ResourceManager.GetString("displayGroupDropDownList_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group 10.
        /// </summary>
        internal static string displayGroupDropDownList_9 {
            get {
                return ResourceManager.GetString("displayGroupDropDownList_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The display group to which this notification type belongs. Only one notification can be active per group..
        /// </summary>
        internal static string displayGroupDropDownListTooltip {
            get {
                return ResourceManager.GetString("displayGroupDropDownListTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Group.
        /// </summary>
        internal static string displayGroupHeader {
            get {
                return ResourceManager.GetString("displayGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Notification.
        /// </summary>
        internal static string displayNotificationButton {
            get {
                return ResourceManager.GetString("displayNotificationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor Anchor.
        /// </summary>
        internal static string monitorAnchorHeader {
            get {
                return ResourceManager.GetString("monitorAnchorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Left.
        /// </summary>
        internal static string notificationAnchorDropDownList_0 {
            get {
                return ResourceManager.GetString("notificationAnchorDropDownList_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Right.
        /// </summary>
        internal static string notificationAnchorDropDownList_1 {
            get {
                return ResourceManager.GetString("notificationAnchorDropDownList_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Left.
        /// </summary>
        internal static string notificationAnchorDropDownList_2 {
            get {
                return ResourceManager.GetString("notificationAnchorDropDownList_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Right.
        /// </summary>
        internal static string notificationAnchorDropDownList_3 {
            get {
                return ResourceManager.GetString("notificationAnchorDropDownList_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The screen anchor to which the offsets should be applied..
        /// </summary>
        internal static string notificationAnchorDropDownListTooltip {
            get {
                return ResourceManager.GetString("notificationAnchorDropDownListTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Length.
        /// </summary>
        internal static string notificationLengthHeader {
            get {
                return ResourceManager.GetString("notificationLengthHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Type List.
        /// </summary>
        internal static string notificationTypeListHeader {
            get {
                return ResourceManager.GetString("notificationTypeListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Show when Tibia is Active.
        /// </summary>
        internal static string onlyShowWhenTibiaIsActiveCheckbox {
            get {
                return ResourceManager.GetString("onlyShowWhenTibiaIsActiveCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite Settings.
        /// </summary>
        internal static string overwriteSettingsHeader {
            get {
                return ResourceManager.GetString("overwriteSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position (Offset).
        /// </summary>
        internal static string positionOffsetHeader {
            get {
                return ResourceManager.GetString("positionOffsetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing.
        /// </summary>
        internal static string testingHeader {
            get {
                return ResourceManager.GetString("testingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Offset.
        /// </summary>
        internal static string xOffsetLabel {
            get {
                return ResourceManager.GetString("xOffsetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Offset.
        /// </summary>
        internal static string yOffsetLabel {
            get {
                return ResourceManager.GetString("yOffsetLabel", resourceCulture);
            }
        }
    }
}
