//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tibialyzer.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PopupsTab {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PopupsTab() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tibialyzer.Translation.PopupsTab", typeof(PopupsTab).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor.
        /// </summary>
        internal static string anchorHeader {
            get {
                return ResourceManager.GetString("anchorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Display.
        /// </summary>
        internal static string clearDisplayButton {
            get {
                return ResourceManager.GetString("clearDisplayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold/Cap Ratio Popup.
        /// </summary>
        internal static string goldCapRatioPopupHeader {
            get {
                return ResourceManager.GetString("goldCapRatioPopupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Value Popup.
        /// </summary>
        internal static string itemValuePopupHeader {
            get {
                return ResourceManager.GetString("itemValuePopupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Left.
        /// </summary>
        internal static string popupAnchorDropDownList_0 {
            get {
                return ResourceManager.GetString("popupAnchorDropDownList_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Right.
        /// </summary>
        internal static string popupAnchorDropDownList_1 {
            get {
                return ResourceManager.GetString("popupAnchorDropDownList_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Left.
        /// </summary>
        internal static string popupAnchorDropDownList_2 {
            get {
                return ResourceManager.GetString("popupAnchorDropDownList_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Right.
        /// </summary>
        internal static string popupAnchorDropDownList_3 {
            get {
                return ResourceManager.GetString("popupAnchorDropDownList_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The screen anchor to which the offsets should be applied..
        /// </summary>
        internal static string popupAnchorDropDownListTooltip {
            get {
                return ResourceManager.GetString("popupAnchorDropDownListTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup Conditions.
        /// </summary>
        internal static string popupConditionsHeader {
            get {
                return ResourceManager.GetString("popupConditionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup Duration.
        /// </summary>
        internal static string popupDurationHeader {
            get {
                return ResourceManager.GetString("popupDurationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup Items.
        /// </summary>
        internal static string popupItemsHeader {
            get {
                return ResourceManager.GetString("popupItemsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup Test.
        /// </summary>
        internal static string popupTestButton {
            get {
                return ResourceManager.GetString("popupTestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test if the specified loot message produces a popup..
        /// </summary>
        internal static string popupTestButtonTooltip {
            get {
                return ResourceManager.GetString("popupTestButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Popup.
        /// </summary>
        internal static string popupTypeDropDownList_0 {
            get {
                return ResourceManager.GetString("popupTypeDropDownList_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rich Popup.
        /// </summary>
        internal static string popupTypeDropDownList_1 {
            get {
                return ResourceManager.GetString("popupTypeDropDownList_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rich notifications are Windows Forms notifications that look pretty. Simple notifications are default Windows bubble notifications..
        /// </summary>
        internal static string popupTypeDropDownListTooltip {
            get {
                return ResourceManager.GetString("popupTypeDropDownListTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup Type.
        /// </summary>
        internal static string popupTypeHeader {
            get {
                return ResourceManager.GetString("popupTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position (Offset).
        /// </summary>
        internal static string positionOffsetHeader {
            get {
                return ResourceManager.GetString("positionOffsetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Gold/Cap Ratio Popup.
        /// </summary>
        internal static string setGoldCapRatioButton {
            get {
                return ResourceManager.GetString("setGoldCapRatioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set it so popups appear when an item drops that has a gold/cap ratio higher than {Ratio}..
        /// </summary>
        internal static string setGoldCapRatioButtonTooltip {
            get {
                return ResourceManager.GetString("setGoldCapRatioButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Item Value Popup.
        /// </summary>
        internal static string setItemValuePopupButton {
            get {
                return ResourceManager.GetString("setItemValuePopupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set it so popups appear when an item drops that is worth more than {Item Value}..
        /// </summary>
        internal static string setItemValuePopupButtonTooltip {
            get {
                return ResourceManager.GetString("setItemValuePopupButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Copy Button.
        /// </summary>
        internal static string showCopyButtonCheckbox {
            get {
                return ResourceManager.GetString("showCopyButtonCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size (Width).
        /// </summary>
        internal static string sizeWidthHeader {
            get {
                return ResourceManager.GetString("sizeWidthHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Display.
        /// </summary>
        internal static string testDisplayButton {
            get {
                return ResourceManager.GetString("testDisplayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing.
        /// </summary>
        internal static string testingHeader {
            get {
                return ResourceManager.GetString("testingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Popup Message.
        /// </summary>
        internal static string testPopupMessageHeader {
            get {
                return ResourceManager.GetString("testPopupMessageHeader", resourceCulture);
            }
        }
    }
}
