//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tibialyzer.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsTab {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsTab() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tibialyzer.Translation.SettingsTab", typeof(SettingsTab).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Advances To Clipboard.
        /// </summary>
        internal static string copyAdvancesCheckbox {
            get {
                return ResourceManager.GetString("copyAdvancesCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you advance in level or skill, the advancement text will be automatically copied for you, so you can easily paste it and notify your friends..
        /// </summary>
        internal static string copyAdvancesCheckboxTooltip {
            get {
                return ResourceManager.GetString("copyAdvancesCheckboxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string defaultOutfitGenderDropDownList_0 {
            get {
                return ResourceManager.GetString("defaultOutfitGenderDropDownList_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string defaultOutfitGenderDropDownList_1 {
            get {
                return ResourceManager.GetString("defaultOutfitGenderDropDownList_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Outfit Gender.
        /// </summary>
        internal static string defaultOutfitGenderHeader {
            get {
                return ResourceManager.GetString("defaultOutfitGenderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outfit gender displayed in outfit@ searches..
        /// </summary>
        internal static string defaultOutfitGenderHeaderTooltip {
            get {
                return ResourceManager.GetString("defaultOutfitGenderHeaderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Popup Animations.
        /// </summary>
        internal static string enablePopupAnimationsCheckbox {
            get {
                return ResourceManager.GetString("enablePopupAnimationsCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether or not popups should be animated or simply appear..
        /// </summary>
        internal static string enablePopupAnimationsCheckboxTooltip {
            get {
                return ResourceManager.GetString("enablePopupAnimationsCheckboxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard (Tibia Client Style).
        /// </summary>
        internal static string experienceComputationDropDownList_0 {
            get {
                return ResourceManager.GetString("experienceComputationDropDownList_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weighted.
        /// </summary>
        internal static string experienceComputationDropDownList_1 {
            get {
                return ResourceManager.GetString("experienceComputationDropDownList_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The algorithm used to compute experience per hour. Standard Tibia Style uses the same algorithm as the Tibia client; while weighted places more emphasis on recent experience gained..
        /// </summary>
        internal static string experienceComputationDropDownListTooltip {
            get {
                return ResourceManager.GetString("experienceComputationDropDownListTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience Computation.
        /// </summary>
        internal static string experienceComputationHeader {
            get {
                return ResourceManager.GetString("experienceComputationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Player Look Information.
        /// </summary>
        internal static string extraPlayerLookInformationCheckbox {
            get {
                return ResourceManager.GetString("extraPlayerLookInformationCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When looking at a player, also navigate to the tibia.com page for that player and gather extra information (e.g. recent deaths, house, guild, marriage)..
        /// </summary>
        internal static string extraPlayerLookInformationCheckboxTooltip {
            get {
                return ResourceManager.GetString("extraPlayerLookInformationCheckboxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Scan Settings.
        /// </summary>
        internal static string memoryScanSettingsHeader {
            get {
                return ResourceManager.GetString("memoryScanSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string optionsHeader {
            get {
                return ResourceManager.GetString("optionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup on Event.
        /// </summary>
        internal static string popupOnEventCheckbox {
            get {
                return ResourceManager.GetString("popupOnEventCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a raid message is send or an achievement is gained, a notification will appear informing you of the event..
        /// </summary>
        internal static string popupOnEventCheckboxTooltip {
            get {
                return ResourceManager.GetString("popupOnEventCheckboxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup Options.
        /// </summary>
        internal static string popupOptionsHeader {
            get {
                return ResourceManager.GetString("popupOptionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Locked).
        /// </summary>
        internal static string resetSettingsButton {
            get {
                return ResourceManager.GetString("resetSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Settings To Default.
        /// </summary>
        internal static string resetSettingsToDefaultHeader {
            get {
                return ResourceManager.GetString("resetSettingsToDefaultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears all settings and resets them back to the default settings, except for the hunt settings..
        /// </summary>
        internal static string resetSettingsToDefaultHeaderTooltip {
            get {
                return ResourceManager.GetString("resetSettingsToDefaultHeaderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Internal Tabs Structure.
        /// </summary>
        internal static string scanInternalTabsCheckbox {
            get {
                return ResourceManager.GetString("scanInternalTabsCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning the internal tab structure is much faster and prevents duplicate issues (only available for C client).\nOnly select scanning the entire memory if for some reason this setting does not work (e.g. because of an update)..
        /// </summary>
        internal static string scanInternalTabsCheckboxTooltip {
            get {
                return ResourceManager.GetString("scanInternalTabsCheckboxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning Options.
        /// </summary>
        internal static string scanningOptionsHeader {
            get {
                return ResourceManager.GetString("scanningOptionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning Speed.
        /// </summary>
        internal static string scanningSpeedHeader {
            get {
                return ResourceManager.GetString("scanningSpeedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the memory scanning speed of Tibialyzer. Lower settings drastically reduce CPU usage, but increase response time for Tibialyzer to respond to events in-game (such as in-game commands, look events and loot parsing)..
        /// </summary>
        internal static string scanningSpeedTrackTooltip {
            get {
                return ResourceManager.GetString("scanningSpeedTrackTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Duplicate Commands.
        /// </summary>
        internal static string skipDuplicateCommandsCheckbox {
            get {
                return ResourceManager.GetString("skipDuplicateCommandsCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Duplicate Loot.
        /// </summary>
        internal static string skipDuplicateLootCheckbox {
            get {
                return ResourceManager.GetString("skipDuplicateLootCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Reset Button.
        /// </summary>
        internal static string unlockResetButton {
            get {
                return ResourceManager.GetString("unlockResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        internal static string unlockResetButtonHeader {
            get {
                return ResourceManager.GetString("unlockResetButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup on Unrecognized Command.
        /// </summary>
        internal static string unrecognizedPopupCheckbox {
            get {
                return ResourceManager.GetString("unrecognizedPopupCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you type in an unrecognized command in Tibia chat (unrecognized@), a notification will appear notifying you of this..
        /// </summary>
        internal static string unrecognizedPopupCheckboxTooltip {
            get {
                return ResourceManager.GetString("unrecognizedPopupCheckboxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Looked At Objects.
        /// </summary>
        internal static string viewLookedAtObjectsCheckbox {
            get {
                return ResourceManager.GetString("viewLookedAtObjectsCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you look (shift+click) at an item, creature or npc in-game, Tibialyzer will automatically open a box displaying information about that object..
        /// </summary>
        internal static string viewLookedAtObjectsCheckboxTooltip {
            get {
                return ResourceManager.GetString("viewLookedAtObjectsCheckboxTooltip", resourceCulture);
            }
        }
    }
}
