//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tibialyzer.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SystemTab {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemTab() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tibialyzer.Translation.SystemTab", typeof(SystemTab).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically Backup Settings.
        /// </summary>
        internal static string automaticallyBackupSettingsCheckbox {
            get {
                return ResourceManager.GetString("automaticallyBackupSettingsCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Settings.
        /// </summary>
        internal static string backupSettingsHeader {
            get {
                return ResourceManager.GetString("backupSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Backup.
        /// </summary>
        internal static string createBackupButton {
            get {
                return ResourceManager.GetString("createBackupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Commands.
        /// </summary>
        internal static string customCommandsHeader {
            get {
                return ResourceManager.GetString("customCommandsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Window Capture.
        /// </summary>
        internal static string enableWindowCaptureCheckbox {
            get {
                return ResourceManager.GetString("enableWindowCaptureCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        internal static string hudAnchorDropDownList_0 {
            get {
                return ResourceManager.GetString("hudAnchorDropDownList_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string hudAnchorDropDownList_1 {
            get {
                return ResourceManager.GetString("hudAnchorDropDownList_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string hudAnchorDropDownList_10 {
            get {
                return ResourceManager.GetString("hudAnchorDropDownList_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        internal static string hudAnchorDropDownList_11 {
            get {
                return ResourceManager.GetString("hudAnchorDropDownList_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string hudAnchorDropDownList_12 {
            get {
                return ResourceManager.GetString("hudAnchorDropDownList_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string hudAnchorDropDownList_13 {
            get {
                return ResourceManager.GetString("hudAnchorDropDownList_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string hudAnchorDropDownList_14 {
            get {
                return ResourceManager.GetString("hudAnchorDropDownList_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string hudAnchorDropDownList_15 {
            get {
                return ResourceManager.GetString("hudAnchorDropDownList_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string hudAnchorDropDownList_2 {
            get {
                return ResourceManager.GetString("hudAnchorDropDownList_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string hudAnchorDropDownList_3 {
            get {
                return ResourceManager.GetString("hudAnchorDropDownList_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string hudAnchorDropDownList_4 {
            get {
                return ResourceManager.GetString("hudAnchorDropDownList_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string hudAnchorDropDownList_5 {
            get {
                return ResourceManager.GetString("hudAnchorDropDownList_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string hudAnchorDropDownList_6 {
            get {
                return ResourceManager.GetString("hudAnchorDropDownList_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string hudAnchorDropDownList_7 {
            get {
                return ResourceManager.GetString("hudAnchorDropDownList_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string hudAnchorDropDownList_8 {
            get {
                return ResourceManager.GetString("hudAnchorDropDownList_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string hudAnchorDropDownList_9 {
            get {
                return ResourceManager.GetString("hudAnchorDropDownList_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Settings From Previous Tibialyzer.
        /// </summary>
        internal static string importSettingsHeader {
            get {
                return ResourceManager.GetString("importSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Damage@ Players.
        /// </summary>
        internal static string maxDamagePlayersHeader {
            get {
                return ResourceManager.GetString("maxDamagePlayersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBS Settings.
        /// </summary>
        internal static string obsSettingsHeader {
            get {
                return ResourceManager.GetString("obsSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string parametersHeader {
            get {
                return ResourceManager.GetString("parametersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Backup.
        /// </summary>
        internal static string restoreBackupButton {
            get {
                return ResourceManager.GetString("restoreBackupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Damage Image.
        /// </summary>
        internal static string saveDamageImageButton {
            get {
                return ResourceManager.GetString("saveDamageImageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves an image of the damage chart (damage@) to a file..
        /// </summary>
        internal static string saveDamageImageButtonTooltip {
            get {
                return ResourceManager.GetString("saveDamageImageButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Images.
        /// </summary>
        internal static string saveImagesHeader {
            get {
                return ResourceManager.GetString("saveImagesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Loot Image.
        /// </summary>
        internal static string saveLootImageButton {
            get {
                return ResourceManager.GetString("saveLootImageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves an image of the loot command (loot@) to a file..
        /// </summary>
        internal static string saveLootImageButtonTooltip {
            get {
                return ResourceManager.GetString("saveLootImageButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Summary Image.
        /// </summary>
        internal static string saveSummaryImageButton {
            get {
                return ResourceManager.GetString("saveSummaryImageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves an image of the summary command (summary@) to a file..
        /// </summary>
        internal static string saveSummaryImageButtonTooltip {
            get {
                return ResourceManager.GetString("saveSummaryImageButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tibialyzer.
        /// </summary>
        internal static string selectUpgradeTibialyzerButton {
            get {
                return ResourceManager.GetString("selectUpgradeTibialyzerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import settings from a previous Tibialyzer. Select the directory in which the previous Tibialyzer is located..
        /// </summary>
        internal static string selectUpgradeTibialyzerButtonTooltip {
            get {
                return ResourceManager.GetString("selectUpgradeTibialyzerButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Popups In Window.
        /// </summary>
        internal static string showPopupWindowButton {
            get {
                return ResourceManager.GetString("showPopupWindowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Command.
        /// </summary>
        internal static string systemCommandHeader {
            get {
                return ResourceManager.GetString("systemCommandHeader", resourceCulture);
            }
        }
    }
}
