plural_maps = dict()
#assorted 
plural_maps['nails'] = 'nail'
plural_maps['skulls'] = 'skull'
#gems
plural_maps['scarab coins'] = 'scarab coin'
plural_maps['small sapphires'] = 'small sapphire'
plural_maps['small diamonds'] = 'small diamond'
plural_maps['small emeralds'] = 'small emerald'
plural_maps['small topazes'] = 'small topaz'
plural_maps['small amethysts'] = 'small amethyst'
plural_maps['small rubies'] = 'small ruby'
plural_maps['black pearls'] = 'black pearl'
plural_maps['white pearls'] = 'white pearl'
plural_maps['orichalcum pearls'] = 'orichalcum pearl'
plural_maps['gold ingots'] = 'gold ingot'
plural_maps['green crystal fragments'] = 'green crystal fragment'
plural_maps['red crystal fragments'] = 'red crystal fragment'
plural_maps['green crystal shards'] = 'green crystal shard'
#arrows
plural_maps['burst arrows'] = 'burst arrow'
plural_maps['crystalline arrows'] = 'crystalline arrow'
plural_maps['earth arrows'] = 'earth arrow'
plural_maps['flaming arrows'] = 'flaming arrow'
plural_maps['flash arrows'] = 'flash arrow'
plural_maps['onyx arrows'] = 'onyx arrow'
plural_maps['shiver arrows'] = 'shiver arrow'
plural_maps['sniper arrows'] = 'sniper arrow'
plural_maps['envenomed arrows'] = 'envenomed arrow'
plural_maps['poison arrows'] = 'poison arrow'
plural_maps['arrows'] = 'arrow'
#bolts
plural_maps['bolts'] = 'bolt'
plural_maps['drill bolts'] = 'drill bolt'
plural_maps['infernal bolts'] = 'infernal bolt'
plural_maps['piercing bolts'] = 'piercing bolt'
plural_maps['power bolts'] = 'power bolt' 
plural_maps['prismatic bolts'] = 'prismatic bolt'
plural_maps['vortex bolts'] = 'vortex bolt'
#spears
plural_maps['spears'] = 'spear'
plural_maps['hunting spears'] = 'hunting spear'
plural_maps['royal spears'] = 'royal spear'
plural_maps['enchanted spears'] = 'enchanted spear'
#other ammunition
plural_maps['small stones'] = 'small stone'
plural_maps['throwing knives'] = 'throwing knife'
plural_maps['snowballs'] = 'snowball'
plural_maps['throwing stars'] = 'throwing star'
plural_maps['viper stars'] = 'viper star'
plural_maps['assassin stars'] = 'assassin star'
#food
plural_maps['bananas'] = 'banana'
plural_maps['oranges'] = 'orange'
plural_maps['white mushrooms'] = 'white mushroom'
plural_maps['brown mushrooms'] = 'brown mushroom'
plural_maps['red mushrooms'] = 'red mushroom'
plural_maps['worms'] = 'worm'